swagger:
  enabled: false
spring:
  dubbo:
    registry:
      address: 'zookeeper://127.0.0.1:2181'
  thymeleaf:
    cache: true
  datasource:
    username: root
    password: root
    url: 'jdbc:mysql://127.0.0.1:3306/db_name'
